# Generated by Django 5.1.2 on 2024-11-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='id',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='candidato_cpf',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
